print('=' * 40)
dias = int(input('Quantos dias o carro foi alugado? '))
km = float(input('Quantos km rodou? '))
valor = (dias * 60) + (km * 0.15)
print('O valor a pagar é R$ {:.2f}'.format(valor))
print('=' * 40)